### ISSUE TITLE
allow alarm to go off after reboot without unlocking device 

### ISSUE THREAD

**Issue by rosemaryuser** [vicolo-dev/chrono#293] opened 2024-06-15 14:43 UTC
**Is your feature request related to a problem? Please describe.**
I was trying to integrate this app to my rom but when i boot the device it will always say Chrono has crashed and after reading the logs i found out that 

> java.lang.RuntimeException: Unable to create service com.flux.flutter_boot_receiver.BootHandlerService: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked

so after some research i found at that this also impacts the alarm as the title mentioned 

**Describe the solution you'd like**
so during my research i found out that u can use Android DirectBoot.
Here is the link to the guide for implementing it 
https://github.com/android/security-samples/tree/master/DirectBoot

**Comment by AhsanSarwar45** [comment] 2024-06-18 08:24
I think this is a duplicate of #102, closing this in favor of that.

**Closed** 2024-06-18 08:24 UTC
