### ISSUE TITLE
extending Timer adds wrong amount

### ISSUE THREAD

**Issue by Maraxi** [vicolo-dev/chrono#311] opened 2024-07-08 09:10 UTC
**Describe the bug**
When a timer expires and time is added from the lock screen it always adds 1 minute instead of the configured value.

**To Reproduce**
1. Go to Settings -> Timer -> Default Settings -> Add Length and change the amount to 15min
2. Start a 1min timer and lock device
3. Click on "+15:00" when the timer expires

**Expected behavior**
The timer is extended for 15 minutes. Instead only 1 minute is added.

**Screenshots**

**Smartphone Information**
 - Device: Samsung S9
 - OS: LineageOS, Android 13
 - App version 0.5.1

**Additional context**
This only occurs from notification or lock screen. When in the app the correct amount is added

**Comment by AhsanSarwar45** [comment] 2024-07-08 09:50
I think this is a duplicate of #288. It has been fixed in [v0.5.2-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.2-beta1). Let me know if it works for you.

**Closed by AhsanSarwar45** 2024-07-08 09:50 UTC
Labels: bug
