### ISSUE TITLE
Alarm can't work when device screen on

### ISSUE THREAD

**Issue by iBabu007** [vicolo-dev/chrono#37] opened 2023-12-16 18:07 UTC
Alarm can't work when device screen on.
The app crashed and alarm tone running background.
And it's (Notification panel) UI is different.

![Screenshot_20231216-213411](https://github.com/vicolo-dev/chrono/assets/65340361/1bdd835b-6ccb-42fe-ba30-35bb4662a046)

**Comment by AhsanSarwar45** [comment] 2023-12-16 18:34
I think the issue is occurs when alarm tasks are added. Can you do the same except with no tasks and see if this happens?

**Comment by AhsanSarwar45** [comment] 2023-12-17 17:00
Fixed in 0.2.10. Feel free to reopen the issue if the problem persists.

**Closed by AhsanSarwar45** 2023-12-17 17:00 UTC
Labels: bug

**Comment by iBabu007** [comment] 2023-12-18 03:26
Hi, dev this issue(Solved task) is solved in 0.2.10
But this time it happened with **dismiss** button.
