### ISSUE TITLE
[BUG] "Next Alarm in" notification even after alarm is skipped

### ISSUE THREAD

**Issue by Rafee-M** [vicolo-dev/chrono#207] opened 2024-05-01 20:03 UTC
**Describe the bug**
While skipping alarm, the notification for the said upcoming alarm shows up

**To Reproduce**
1. Create an alarm
2. Skip it
3. Wait for it's time to see notification

**Expected behavior**
When skipped, notification shouldn't be present

**Screenshots**
**Alarm notification:**
![image](https://github.com/vicolo-dev/chrono/assets/69535896/5e58d8ae-6c7a-4532-8fc5-e01cde79d250)

**Alarm skipped:**
![image](https://github.com/vicolo-dev/chrono/assets/69535896/d9011dac-600d-4231-b28b-46169dcc1074)

**Smartphone Information**
 - Device: OnePlus 9
 - OS: Android 13
 - App version: 0.4.3

**Additional context**
First time using these steps, so can't confirm if it was present before the update. Also, thanks for your hard work maintaining the app and all the useful features you've added. Thanks a lot!

**Comment by jgilmore** [comment] 2024-05-12 15:11
This also happens if the alarm isn't skipped, but doesn't go off anyway. Even hours (but not days) later the notification about an upcoming alarm will still be there.

**Comment by th23x** [comment] 2024-05-14 11:53
Seconding the above mentioned behaviour - and the (wrong) notification even reappears once "dismissed"

**Comment by AhsanSarwar45** [comment] 2024-05-15 14:19
Just to confirm, the notification appears when the alarm was supposed to ring, right? 
Say I have an alarm for 9:30.
1. I skip it
2. At 9:30, alarm doesn't ring, like expected. 
3. But at 9:30, an 'upcoming alarm' notification gets created. 

This is the case that I have been able to reproduce. Let me know if this is your case as well or something different.

**Comment by th23x** [comment] 2024-05-15 15:52
Yes, that's the behavior I experienced as well 👍

**Comment by AhsanSarwar45** [comment] 2024-05-18 11:40
This should be fixed in the [v0.5.0-beta2](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.0-beta2) release. Let me know if there are any issues with it.

**Closed by AhsanSarwar45** 2024-05-18 11:40 UTC
Labels: bug

**Comment by th23x** [comment] 2024-05-18 20:09
Excellent, works for me now as expected 👍
