### ISSUE TITLE
Error decoding string: FormatException: Unexpected character (at character 18943)

### ISSUE THREAD

**Issue by AndyMagnom** [vicolo-dev/chrono#375] opened 2024-11-10 12:05 UTC
**Describe the bug**
Error message on beta 0.6.0-beta1 :

Error decoding string: FormatException: Unexpected character (at character 18943)

...vice] Update alarms in background service","isActive":false}]ctive":false}]

**To Reproduce**
1. Open Chrono, Set alarms and Use it normally for couple of days
2. Suddenly alarms stop working
3. Open Chrono again
5. Force stop & clear cache
6. Open Chrono again, See error
7. Clear storage data
8. Error doesn't appear
9. Repeat from step 2

**Expected behavior**
Set alarms and Alarms work even when I don't open the app for days and the Error doesn't appear

**Screenshots**
Added!

**Smartphone Information**
 - Device: Realme C53 RMX3760
 - OS: 14
 - App version: beta 0.6.0-beta1 

**Additional context**
I prevented the system from killing Background processes but it still gives me the same error after days from setting it up

**Comment by AhsanSarwar45** [comment] 2024-11-11 15:11
Duplicate of #355, let's continue the discussion there.

**Closed by AhsanSarwar45** 2024-11-11 15:11 UTC
Labels: bug
