### ISSUE TITLE
Restarting the phone causes an alarm to go off

### ISSUE THREAD

**Issue by mizu-048** [vicolo-dev/chrono#90] opened 2023-12-26 18:20 UTC
**Describe the bug**
When i restart my phone after things load up, an alarm goes off. The alarm is one i made but its not enabled and its not it's time yet and its just this specific alarm(8:25 AM as visible in the given screenshots) going off, no other

**To Reproduce**
may not work for everyone but here you go
1. Restart your phone
2. Unlock the lockscreen
3. Wait for things to load up, mainly after syncing contacts notif.
4. if you put your phone to sleep you will get the splash if you kept it woke you will get the notif alarm

**Expected behavior**
an alarm shouldn't go off

**Screenshots**
![Screenshot_20231226-131723.png](https://github.com/vicolo-dev/chrono/assets/154871713/2ae0593a-8375-4644-8473-be8a6260499d)

![Screenshot_20231226-230840.png](https://github.com/vicolo-dev/chrono/assets/154871713/ecb3210c-5e6f-41df-b1e9-99e9ac367f0c)

![Screenshot_20231226-230009.png](https://github.com/vicolo-dev/chrono/assets/154871713/d331c4b3-9d69-43ad-b619-041cf1be5641)

![Screenshot_20231226-230847.png](https://github.com/vicolo-dev/chrono/assets/154871713/8baa860a-81a9-4868-a7c9-cdb1c62ad0c1)

**Smartphone Information**
 - Device: [Sparx neo 7]
 - OS: [Android 12]
 - App version [0.2.10] 

**Additional Information**

i tried enabling another alarm(7:50 AM , as seen in the last screenshots) but that didn't change which alarm is shown upon restarting

**Comment by AhsanSarwar45** [comment] 2024-03-20 12:17
Can u reproduce this issue after re-installing the app?

**Comment by mizu-048** [comment] 2024-03-20 16:23
so i've reset my device and obviously installed the app since i reported this issue and the bug is not occuring anymore. I will update the issue if in future it happens again.

**Comment by mizu-048** [comment] 2024-03-26 16:05
nevermind, i just tried it again and its still happening![Screenshot_20240326-210425.png](https://github.com/vicolo-dev/chrono/assets/154871713/64296952-a3ab-4ccb-96b6-a08d1532a616)

**Comment by mizu-048** [comment] 2024-03-26 23:44
1-  the alarm that rung this time was the one that i had just used to wake up. so it is from the alarms i have made, not the current time.

2- yes, about that i just found a new bug, where even with no alarm enabled, an icon is showing and its from chrono, clicking on it produces the [#103](https://github.com/vicolo-dev/chrono/issues/103) issue. stopping the app makes it disappear, opening the app again it remains disappeares. Restarting brought it back.

3- due to what i explain in answer 2, the icon appeared 10 seconds after unlocking the screen, but it took about a full minute for the alarms to actually ring


extra: its not a single alarm that rings, its multiple alarms, checking notification history i see a notification for each of the alarms i **recently used**.
![Screenshot_20240327-043401_1.png](https://github.com/vicolo-dev/chrono/assets/154871713/5572c141-2fab-4e6e-9107-857f8d6544f3)

**Comment by mizu-048** [comment] 2024-03-28 00:13
so an update on the issue with more things to confuse are these:
![Screenshot_20240328-050915_1.png](https://github.com/vicolo-dev/chrono/assets/154871713/5054673e-4ce0-4150-bbbe-d9e2ee862223)

![Screenshot_20240328-050843.png](https://github.com/vicolo-dev/chrono/assets/154871713/e417e791-cb49-4f09-ab49-6179abce5444)

the alarm showed up as 3:35 but when i clicked it, it displayed my current time

**Comment by mizu-048** [comment] 2024-03-28 00:19
another thing to add is that i edited my 4:15 alarm to 3:50 last night which did ring but in the restart bug, i still see 4:15 so something with cache?

**Comment by Rafee-M** [comment] 2024-03-28 06:55
Can reproduce this as well on OxygenOS 14, Android 14

**Comment by AhsanSarwar45** [comment] 2024-03-28 07:55
So I think the first thing that needs to be done is to implement an alarm logging/tracking system which allows the user to see all events of alarms being set or cancelled within developer options. It should also show description of what part of the code called the setting of the alarm. That will allow us to better understand what causes this issue, as well as future such issues, because these can be difficult to reproduce.

**Comment by AhsanSarwar45** [comment] 2024-04-04 17:45
So I have released the beta release on github: https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta5. Please test it out to see if this still occurs. If yes, then go to Settings > Developer Options > Alarm Logs and click the download button to save the logs to a file. Then send that file here.

**Comment by AhsanSarwar45** [comment] 2024-04-09 16:43
@mizu-048 Have you been able to reproduce this with lastest releases?

**Comment by mizu-048** [comment] 2024-04-09 16:46
i have restarted a few times since then but it didn't occur, Will inform you if it happens again with the logs

**Comment by AhsanSarwar45** [comment] 2024-04-09 17:32
Closing this for now, but if it occurs again, feel free to re-open.

**Closed by AhsanSarwar45** 2024-04-09 17:32 UTC
Labels: bug
